// <auto-generated />
namespace WebApiCodeBaseToken.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddErrorLogger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddErrorLogger));
        
        string IMigrationMetadata.Id
        {
            get { return "202404071754044_AddErrorLogger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
